<a href="https://colab.research.google.com/github/guilourenzo/mba-usp/blob/master/T%C3%89CNICAS%20AVAN%C3%87ADAS%20DE%20CAPTURA%20E%20TRATAMENTO%20DE%20DADOS/AULA%206/docXpala%20avaliacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Técnicas Avançadas para Captura e Tratamento de Dados</span>

## <span style="color:blue"> Matriz Documento $\times$ Palavras - Bag of Words</span>
    
## <span style="color:blue">Avaliação</span>

**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

Os exercícios abaixo fazem uso da coleção de documentos presente no diretório `DocCol2` contido no arquivo <font style="font-family: monaco"> DocCol.zip</font>, o qual pode ser baixado do Moodle.

In [1]:
from google.colab import files
uploaded = files.upload()

Saving au1 to au1
Saving au2 to au2
Saving au3 to au3
Saving au4 to au4
Saving au5 to au5
Saving au6 to au6
Saving au7 to au7
Saving au8 to au8
Saving au9 to au9
Saving au10 to au10
Saving au11 to au11
Saving au12 to au12
Saving au13 to au13
Saving au14 to au14
Saving au15 to au15
Saving ch1 to ch1
Saving ch2 to ch2
Saving ch3 to ch3
Saving ch4 to ch4
Saving ch5 to ch5
Saving ch6 to ch6
Saving ch7 to ch7
Saving ch8 to ch8
Saving ch9 to ch9
Saving ch10 to ch10
Saving ch11 to ch11
Saving ch12 to ch12
Saving ch13 to ch13
Saving ch14 to ch14
Saving ch15 to ch15
Saving ch16 to ch16
Saving ch17 to ch17
Saving ch18 to ch18
Saving ch19 to ch19
Saving ch20 to ch20
Saving ch21 to ch21
Saving ch22 to ch22
Saving ch23 to ch23
Saving ch24 to ch24
Saving ch25 to ch25
Saving ch26 to ch26
Saving ch27 to ch27
Saving ch28 to ch28
Saving ch29 to ch29
Saving ch30 to ch30
Saving ch31 to ch31
Saving ch32 to ch32
Saving ch33 to ch33
Saving ch34 to ch34
Saving ch35 to ch35
Saving ch36 to ch36
Saving ch37 to c

In [0]:
import glob
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

### Exercício 1)
Armazene os documentos disponíveis no diretório `DocCol2` em um dicionário onde a chave é o nome do arquivo e o valor é a string contida no arquivo. O documento contendo a string com o maior número de caracteres é:

a) gr7<br>
b) au2 <br>
c) ch5<br>
d) au8

In [3]:
# Lendo o documento como uma string
import glob  # glob é um pacote que permite varrer arquivos e 
             # diretorios utilizando sintaxe linux

files = glob.glob("*")

files.pop()

docs = {}
for fname in files:
    with open(fname,'r') as f:
        key = fname.split('/')[-1]
        docs[key] = f.read() 
        
print(docs.keys())

dict_keys(['ch27', 'gr20', 'au1', 'ch48', 'gr4', 'ch10', 'ch46', 'gr6', 'ch1', 'gr10', 'ch39', 'gr7', 'au2', 'ch16', 'ch34', 'ch19', 'gr17', 'ch36', 'ch40', 'au10', 'gr19', 'ch25', 'ch14', 'ch47', 'au7', 'gr18', 'ch21', 'ch11', 'ch8', 'ch35', 'ch49', 'gr12', 'gr23', 'ch37', 'ch4', 'gr3', 'au4', 'au14', 'ch38', 'ch13', 'ch29', 'ch33', 'ch45', 'ch43', 'ch28', 'gr9', 'gr24', 'ch17', 'gr14', 'ch30', 'gr26', 'gr13', 'au3', 'gr5', 'au5', 'ch18', 'ch50', 'ch12', 'gr2', 'au15', 'gr15', 'ch22', 'ch20', 'au13', 'ch31', 'gr16', 'ch2', 'ch32', 'ch42', 'ch15', 'ch7', 'ch6', 'gr25', 'gr21', 'ch24', 'ch3', 'gr11', 'au11', 'gr1', 'gr22', 'ch44', 'au12', 'au8', 'gr8', 'ch26', 'au6', 'ch5', 'au9', 'ch23', 'ch9', 'ch41'])


In [4]:
docs['gr3']

"From: robert@cpuserver.acsc.com (Robert Grant)\nSubject: Virtual Reality for X on the CHEAP!\n\nHi everyone,\n\nI thought that some people may be interested in my VR\nsoftware on these groups:\n\n*******Announcing the release of Multiverse-1.0.2*******\n\nMultiverse is a multi-user, non-immersive, X-Windows based Virtual Reality\nsystem, primarily focused on entertainment/research.\n\nFeatures:\n\n   Client-Server based model, using Berkeley Sockets.\n   No limit to the number of users (apart from performance).\n   Generic clients.\n   Customizable servers.\n   Hierachical Objects (allowing attachment of cameras and light sources).\n   Multiple light sources (ambient, point and spot).\n   Objects can have extension code, to handle unique functionality, easily\n        attached.\n\nFunctionality:\n\n  Client:\n   The client is built around a 'fast' render loop. Basically it changes things\n   when told to by the server and then renders an image from the user's\n   viewpoint. It also pr

In [5]:
valor = 0
chave = ''

for key, values in docs.items():
    # print(len(values))
    if len(values) > valor:
        valor = len(values)
        chave = key

print(chave, valor)

au2 11672


## RESPOSTA:<br>
**LETRA B**

### Exercício 2)
Crie um dicionário chamado `docsXwords` onde as chaves são os nomes dos arquivos e <br> 1. os valores são as listas de palavras do documento correspondente.<br>2. As palavras em cada uma das listas devem ser constituídas apenas por letras do alfabeto,<br>3. estarem lexicamente normalizadas e<br>4.  conterem mais que 1 caracter. <br><br>Qual o documento cuja lista de palavras resultante possui o **maior** número de palavras repetidas:

a) gr22<br>
b) ch30<br>
c) au2<br>
d) au8

In [6]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [7]:
nltk.word_tokenize(docs['gr3'])

['From',
 ':',
 'robert',
 '@',
 'cpuserver.acsc.com',
 '(',
 'Robert',
 'Grant',
 ')',
 'Subject',
 ':',
 'Virtual',
 'Reality',
 'for',
 'X',
 'on',
 'the',
 'CHEAP',
 '!',
 'Hi',
 'everyone',
 ',',
 'I',
 'thought',
 'that',
 'some',
 'people',
 'may',
 'be',
 'interested',
 'in',
 'my',
 'VR',
 'software',
 'on',
 'these',
 'groups',
 ':',
 '*******Announcing',
 'the',
 'release',
 'of',
 'Multiverse-1.0.2*******',
 'Multiverse',
 'is',
 'a',
 'multi-user',
 ',',
 'non-immersive',
 ',',
 'X-Windows',
 'based',
 'Virtual',
 'Reality',
 'system',
 ',',
 'primarily',
 'focused',
 'on',
 'entertainment/research',
 '.',
 'Features',
 ':',
 'Client-Server',
 'based',
 'model',
 ',',
 'using',
 'Berkeley',
 'Sockets',
 '.',
 'No',
 'limit',
 'to',
 'the',
 'number',
 'of',
 'users',
 '(',
 'apart',
 'from',
 'performance',
 ')',
 '.',
 'Generic',
 'clients',
 '.',
 'Customizable',
 'servers',
 '.',
 'Hierachical',
 'Objects',
 '(',
 'allowing',
 'attachment',
 'of',
 'cameras',
 'and',
 '

In [0]:
docsXwords = {}

for key, value in docs.items():
    words = nltk.word_tokenize(value) #CRIA A LISTA DE PALAVRAS
    words = [w.lower() for w in words if w.isalpha() and len(w) != 1] # JOGA PRA MINUSCULO - VERIFICA SE SÃO ALFABÉTICAS E COM MAIS DE 1 CARACTER
    words = [PorterStemmer().stem(w) for w in words] # FAZ A NORMALIZAÇÃO LÉXICA DA LISTA
    docsXwords[key] = words

In [9]:
docsXwords['gr3']

['from',
 'robert',
 'robert',
 'grant',
 'subject',
 'virtual',
 'realiti',
 'for',
 'on',
 'the',
 'cheap',
 'hi',
 'everyon',
 'thought',
 'that',
 'some',
 'peopl',
 'may',
 'be',
 'interest',
 'in',
 'my',
 'vr',
 'softwar',
 'on',
 'these',
 'group',
 'the',
 'releas',
 'of',
 'multivers',
 'is',
 'base',
 'virtual',
 'realiti',
 'system',
 'primarili',
 'focus',
 'on',
 'featur',
 'base',
 'model',
 'use',
 'berkeley',
 'socket',
 'no',
 'limit',
 'to',
 'the',
 'number',
 'of',
 'user',
 'apart',
 'from',
 'perform',
 'gener',
 'client',
 'customiz',
 'server',
 'hierach',
 'object',
 'allow',
 'attach',
 'of',
 'camera',
 'and',
 'light',
 'sourc',
 'multipl',
 'light',
 'sourc',
 'ambient',
 'point',
 'and',
 'spot',
 'object',
 'can',
 'have',
 'extens',
 'code',
 'to',
 'handl',
 'uniqu',
 'function',
 'easili',
 'attach',
 'function',
 'client',
 'the',
 'client',
 'is',
 'built',
 'around',
 'render',
 'loop',
 'basic',
 'it',
 'chang',
 'thing',
 'when',
 'told',
 'to',


In [0]:
# unificando todas as palavras em uma única lista
corpus = [palavras for sublista in list(docsXwords.values()) for palavras in sublista]

# removendo repeticoes
corpus = list(set(corpus))

df_dXp = pd.DataFrame(data=np.zeros((len(list(docs.keys())),len(corpus))),
                      index = list(docs.keys()), columns = corpus)

for key,value in docsXwords.items():
    dtemp = dict(Counter(value))
    df_dXp.loc[key,list(dtemp.keys())] = list(dtemp.values())

In [11]:
rep = {}
for key, values in docsXwords.items():
    count = dict(Counter(values))
    rep[key] = np.sum(np.array(list(count.values()))) - len(count)

print(sorted(rep.items(), key=lambda kv: kv[1], reverse=True))
print(5*'**')
print(max(rep, key=rep.get))

[('ch30', 1128), ('au2', 1112), ('ch24', 1031), ('gr23', 1009), ('ch21', 1005), ('ch44', 988), ('gr25', 981), ('ch18', 963), ('ch36', 920), ('au14', 911), ('ch28', 907), ('ch40', 896), ('ch17', 895), ('ch9', 895), ('ch25', 857), ('ch8', 853), ('ch48', 847), ('ch39', 847), ('ch6', 796), ('ch26', 792), ('ch33', 791), ('ch43', 778), ('ch35', 760), ('ch12', 757), ('au12', 756), ('ch19', 733), ('ch16', 729), ('au5', 727), ('ch41', 704), ('ch4', 693), ('ch47', 690), ('ch46', 682), ('ch10', 674), ('ch29', 669), ('ch3', 660), ('ch22', 658), ('gr26', 655), ('ch23', 651), ('ch32', 650), ('ch20', 642), ('ch45', 637), ('ch50', 636), ('gr22', 635), ('ch14', 611), ('ch2', 611), ('ch37', 606), ('ch1', 605), ('gr24', 604), ('ch27', 601), ('ch38', 597), ('ch15', 597), ('ch11', 584), ('ch5', 583), ('ch49', 558), ('au7', 552), ('ch42', 549), ('au13', 547), ('ch7', 539), ('ch34', 520), ('gr3', 518), ('gr4', 509), ('au8', 505), ('gr18', 498), ('gr10', 495), ('au15', 488), ('gr19', 486), ('gr8', 469), ('ch3

In [12]:
Counter(docsXwords['gr3'])

Counter({'abl': 1,
         'about': 1,
         'accept': 1,
         'action': 1,
         'activ': 1,
         'adapt': 2,
         'add': 1,
         'address': 1,
         'all': 2,
         'allow': 2,
         'also': 2,
         'amateur': 1,
         'ambient': 2,
         'an': 7,
         'and': 17,
         'ani': 1,
         'anim': 1,
         'animateworld': 1,
         'anyon': 3,
         'anyth': 1,
         'apart': 1,
         'applic': 4,
         'are': 2,
         'around': 1,
         'as': 2,
         'associ': 1,
         'assumpt': 1,
         'at': 3,
         'attach': 2,
         'avoid': 1,
         'away': 1,
         'bad': 1,
         'base': 2,
         'basic': 5,
         'be': 13,
         'becaus': 3,
         'berkeley': 1,
         'bit': 1,
         'both': 1,
         'build': 1,
         'built': 1,
         'but': 2,
         'by': 3,
         'ca': 1,
         'call': 2,
         'callback': 2,
         'camera': 1,
         'can': 8,
     

In [13]:
df_dXp

sad  min  edb  camaro  belt  ...  twist  motiv  increas  sig  iron
ch27  0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      1.0  0.0   0.0
gr20  0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
au1   0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
ch48  0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
gr4   0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
...   ...  ...  ...     ...   ...  ...    ...    ...      ...  ...   ...
ch5   0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
au9   0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
ch23  0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
ch9   0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0
ch41  0.0  0.0  0.0     0.0   0.0  ...    0.0    0.0      0.0  0.0   0.0

[91 rows x 6861 columns]

In [14]:
df_dXp.loc['au2',:]

sad        0.0
min        0.0
edb        0.0
camaro     0.0
belt       0.0
          ... 
twist      0.0
motiv      0.0
increas    0.0
sig        0.0
iron       0.0
Name: au2, Length: 6861, dtype: float64

In [15]:
print(df_dXp.sum(axis=1).sort_values(ascending=False))

au2     1665.0
ch30    1518.0
au14    1491.0
ch44    1471.0
ch28    1421.0
         ...  
gr7      460.0
au3      442.0
gr17     435.0
gr12     346.0
gr5      256.0
Length: 91, dtype: float64


## RESPOSTA:<br>
**LETRA D**

### Exercício 3)
Utilizando as listas de palavras do dicionário `docsXwords`, quais as três palavras que mais aparecem na coleção de documentos:

a) the, is, of<br>
b) that, is, of<br>
c) the, of, to <br>
d) to, is, of

In [16]:
df_dXp.sum(axis=0).sort_values(ascending=False)

the          5012.0
of           2627.0
to           2611.0
and          2093.0
is           1762.0
              ...  
carnforth       1.0
terrorist       1.0
outrag          1.0
noew            1.0
sad             1.0
Length: 6861, dtype: float64

## RESPOSTA:<br>
**LETRA C**

### Exercício 4)
Qual o documento cuja lista de palavras possui o **menor** número de "stop words"? Quantas "stop words" aparecem neste documento:

a) gr5 com 47 "stop words"<br>
b) gr17 com 47 "stop words"<br>
c) gr5 com 37 "stop words"<br>
d) gr17 com 37 "stop words"

**Dica**: Crie um dicionário onde a chave é o nome do documento e o valor o número de stop words no documento.

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
doc_stop = {}

stop_words = stopwords.words('english')

for key, value in docsXwords.items():
    words = [w for w in value if w in stop_words]
    doc_stop[key] = len(words)


print(sorted(doc_stop.items(), key=lambda kv: kv[1], reverse=False)[0])


('gr5', 47)


In [19]:
doc_stop['gr3']

338

In [20]:
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

## RESPOSTA:<br>
**LETRA A**

### Exercício 5) 
Utilize o dicionário `docsXwords` para construir
uma matriz Documentos $\times$ Palavras para a coleção de documentos do diretório `DocCol2`. Utilizando a distância cosseno, qual é o documento mais parecido com o documento 'ch7':

a) ch8<br>
b) ch16<br>
c) ch5<br>
d) au8

In [21]:
# encontrando o indice da linha de 'ch7' no DataFrame
ch7_id = np.argwhere(df_dXp.index.values=='ch7')[0][0]

X = df_dXp.values
X = StandardScaler().fit_transform(X)

# calculando o cosseno utilizando a formula
# cos(x,y) = np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
cosch7 = np.apply_along_axis(lambda x: 
             np.dot(X[ch7_id],x)/(np.linalg.norm(ch7_id)*np.linalg.norm(x)),1,X)

# ordenando e pegando o maior valor (note que o elemento [-1] é o 
# próprio documento ch7)
sim_ch7_id = np.argsort(cosch7)[-2]
print('Documento mais parecido com ch7: ',df_dXp.index.values[sim_ch7_id])

Documento mais parecido com ch7:  ch16


In [22]:
cosch7

array([-1.33332689e-02, -2.52525387e-02,  3.10583825e-03, -2.33781837e-02,
       -2.74249492e-02,  1.76331144e-02, -1.29975389e-02, -1.05062935e-02,
        4.63319874e-03, -1.87045486e-02, -3.07366111e-03, -9.54097669e-03,
       -2.37200303e-02,  2.20340972e-02, -1.18626727e-02, -2.55049413e-02,
       -1.54699008e-02, -3.79128353e-03,  4.59236358e-03, -7.01491970e-03,
       -1.15486667e-02, -4.39467726e-03,  1.35516064e-02,  5.22983988e-04,
       -2.16639330e-02, -1.86917361e-02, -1.44996512e-02,  1.20849661e-02,
       -1.80991296e-02, -1.49541772e-02, -9.52627978e-03,  1.52541148e-03,
       -1.04737020e-02, -2.39148372e-02, -2.48901709e-03, -1.46865868e-02,
       -2.39620721e-04, -3.20674510e-02, -1.01558689e-02,  1.29245507e-02,
       -1.27744403e-03, -1.72950095e-02,  2.14839141e-03, -7.63874179e-03,
       -1.84329985e-02, -2.12743410e-02, -1.60164048e-02,  2.07448825e-02,
       -2.15657052e-02, -6.37511611e-03, -5.12154974e-03, -2.12104022e-02,
       -9.27111116e-03,  

In [23]:
np.argsort(cosch7)[-2]

13

In [24]:
np.argwhere(df_dXp.index.values=='ch7')[0][0]

70

In [25]:
X = df_dXp.values
print(X)
X = StandardScaler().fit_transform(X)

print(X)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[-0.10540926 -0.10540926 -0.10540926 ...  4.14728827 -0.10540926
  -0.24112141]
 [-0.10540926 -0.10540926 -0.10540926 ... -0.24112141 -0.10540926
  -0.24112141]
 [-0.10540926 -0.10540926 -0.10540926 ... -0.24112141 -0.10540926
  -0.24112141]
 ...
 [-0.10540926 -0.10540926 -0.10540926 ... -0.24112141 -0.10540926
  -0.24112141]
 [-0.10540926 -0.10540926 -0.10540926 ... -0.24112141 -0.10540926
  -0.24112141]
 [-0.10540926 -0.10540926 -0.10540926 ... -0.24112141 -0.10540926
  -0.24112141]]


## RESPOSTA:<br>
**LETRA B**