#### EXERCÍCIO 1

In [1]:
import numpy as np

In [2]:
A = np.zeros((4,4))
v = np.arange(4)

In [3]:
A[:] = v[:,np.newaxis]
print(A)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [4]:
A[:] = v
A = A.T
print(A)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [5]:
A[:] = v.reshape(4,1)
print(A)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


#### EXERCÍCIO 2

In [8]:
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
print(W, u, v)

[[20 28 43 44 19 35 28]
 [23 31 46 47 22 38 31]
 [19 27 42 43 18 34 27]
 [20 28 43 44 19 35 28]
 [ 7 15 30 31  6 22 15]
 [32 40 55 56 31 47 40]
 [28 36 51 52 27 43 36]
 [16 24 39 40 15 31 24]
 [33 41 56 57 32 48 41]
 [31 39 54 55 30 46 39]] [ 4 12 27 28  3 19 12] [[16]
 [19]
 [15]
 [16]
 [ 3]
 [28]
 [24]
 [12]
 [29]
 [27]]


#### EXERCÍCIO 3

In [52]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7],
            [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0],
            [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1],
            [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4],
            [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
print(A)

[[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]


In [18]:
l_m = np.argmax(np.sum(A,axis=1))
print(l_m)

8


#### EXERCÍCIO 4

In [21]:
c_m = np.argmin(np.mean(A,axis=0))
print(c_m)

2


#### EXERCÍCIO 5

In [53]:
print(A)
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
# print(np.arange(A.shape[0]), '\n\n', Aargs[:,-1], '\n\n', A[np.arange(A.shape[0]),Aargs[:,-1]], '\n\n', Aargs,'\n\n', A)

print('ÍNDICE DA LINHA: ', np.arange(A.shape[0]),'\n ÍNDICE DA COLUNA: ', Aargs[:,-1], '\n\n', A, '\n\n')
 
for i in range(A.shape[0]):
    print('Indices dos elementos ordenados na linha ',i,': ',Aargs[i])
    print('Linha',i,': '+10*' ',A[i])
    print('Linha ',i,' ordenada: ',A[i,Aargs[i]],'\n')

[[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]
ÍNDICE DA LINHA:  [0 1 2 3 4 5 6 7 8 9] 
 ÍNDICE DA COLUNA:  [9 7 0 7 6 3 5 3 7 6] 

 [[ 5  2  3  6  1  5  7  7  8 -1]
 [ 8  8  3  5  0  1  4 -1  3  7]
 [-1  0  0  4  2  0  2  6  0  3]
 [ 5  0  0  4  4  3  5 -1  0  0]
 [ 2  4  2  5  3  4 -1  8  0  0]
 [ 6  7  4 -1  5  1  3  5  4  1]
 [ 6  8  0  5  2 -1  3  6  1  6]
 [ 5  5  2 -1  0  5  5  8  2  4]
 [ 8  8  1  8  4  1  8 -1  7  6]
 [ 5  6  0  9  0  4 -1  0  2  0]] 


Indices dos elementos ordenados na linha  0 :  [4 1 2 0 5 3 6 7 8 9]
Linha 0 :            [ 5  2  3  6  1  5  7  7  8 -1]
Linha  0  ordenada:  [ 1  2  3  5  5  6  7  7  8 -1] 

Indices dos elementos ordenados na linha  1 :  [4 5 2 8 6 3 9 0 1 7]
Linha 1 :            [ 8  8  3  5  0  1  4 -1  3  7]
Linha  1  ordenada:  [ 0  1  3  3  4  5  7  8  8 -