# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
   ---

__Conteúdo:__

- Numpy - Parte I:
  - Visão geral
  - Básico de arrays
  - Manipulação das dimensões
  - Iterar e repartir
  - Indexação estilosa
  - Cópias e visualizações
- I/O com Numpy
  - Leitura e escrita de arrays
  
__Referencias:__

[Numpy Tutorial](https://www.python-course.eu/numpy.php)

---

## Numpy 
<font color='blue'>Numpy</font> é um pacote Python para processamento matricial (computação orientada a matriz) onde:
- as classes e métodos são majoritariamente escrito em C, garantindo eficiência computacional
- possui muitos recursos para computação científica e problemas de álgebra linear

Vários outros pacotes do Python dependem fortemente do <font color='blue'>numpy</font> , como por exemplo:
- pandas
- matplotlib
- sklearn

Numpy é um pacote, precisa portanto ser importado. A forma típica de importar o <font color='blue'>numpy</font> é
```python
import numpy as np
```
porém, outras formas também podem ser utilizadas, como por exemplo:
```python
import numpy
from numpy import *
```

A estruta de dados base do <font color='blue'>numpy</font> são os `arrays`, que funcionam de forma semelhante às listas em Python, no entanto:
- Todo elemento em um array deve ser do mesmo tipo, tipicamente um tipo numérico como <font color='blue'>float</font> ou <font color='blue'>int</font>
- Os arrays viabilizam a realização eficiente de operações numéricas envolvendo grandes quantidades de dados, sendo para este fim, muito mais eficientes que as listas.
- Cada dimensão de um array é chamada de eixo (_axis_)
- Os eixos são numerados a partir de $0$
- Os elementos são acessados utilizando colchetes <font color='blue'>[]</font> (semelhante às listas do Python)

### Construindo arrays
Arrays podem ser construidos de muitas formas diferentes:
- convertendo listas
- via métodos do <font color='blue'>numpy</font>
- convertendo DataFrames

In [2]:
import numpy as np

# criando um array unidimensional a partir de uma lista
print("1D array",5*'-','\n')

lst = [1,3,5,7,9,10]
a1d = np.array(lst)
print(a1d)

# note que na impressão de um array, as vírgulas entre elementos não aparecem como no caso de listas
print(lst)

1D array ----- 

[ 1  3  5  7  9 10]
[1, 3, 5, 7, 9, 10]


In [4]:
# Criando arrays unidimensionais a partir de métodos do numpy
b1d = np.zeros((8))  # array com oito elementos iguais a zero
print('b1d=',b1d)

c1d = np.ones((10))  # array com oito elementos iguais a um
print('c1d=',c1d)

d1d = np.arange(10)  # array com numeros entre 0 e 9
print('d1d=',d1d)

e1d = np.linspace(1,2,5) #array com 5 números igualmente espaçados no intervalo entre 1 e 2 
print('e1d=',e1d)

b1d= [0. 0. 0. 0. 0. 0. 0. 0.]
c1d= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
d1d= [0 1 2 3 4 5 6 7 8 9]
e1d= [1.   1.25 1.5  1.75 2.  ]


In [5]:
# Criando array bidimensional (matriz) a partir de uma lista de listas
print("\n 2D array",5*'-','\n')
a2d = np.array([[1,3,5,7,9,11],
                  [2,4,6,8,10,12],
                  [0,1,2,3,4,5]])
print('a2d=\n',a2d)


 2D array ----- 

a2d=
 [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]


In [9]:
# Criando arrays ubidimensionais a partir de métodos do numpy
b2d = np.zeros((5,3))  # criando matriz 5X3 de zeros
print('b2d=\n',b2d)

c2d = np.ones((5,10))  # criando matriz 5X10 de uns
print('c2d=\n',c2d)

d2d = np.identity(3) # criando matrix identidade 3X3
print('d2d=\n',d2d)

b2d=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
c2d=
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
d2d=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Numpy arrays são objetos chamados _ndarrays_ e possuem diversos atributos 
- ndarray.ndim - número de eixos (dimensões) do array
- ndarray.shape - uma tupla de inteiros indicando o tamanho do array em cada dimensão
- ndarray.size - o número total de elementos do array
- ndarray.dtype - tipo dos elementos no array
- ndarray.itemsize - o tamanho em bytes de cada elemento do array
- ndarray.data - o buffer de memória contendo os elementos do array

In [10]:
# considere os arrays 'a1d', 'b1d', 'a2d', 'b2d' e 'c2d' criados nas células anteriores
print(" ndim: numero de eixos dos arrays")
print('a1d.ndim =',a1d.ndim)
print('b1d.ndim =',b1d.ndim)
print('a2d.ndim =',a2d.ndim)
print('c2d.ndim =',c2d.ndim)

print("\n shape: tamanho do array em cada dimensao")
print('a1d.shape =',a1d.shape)
print('b1d.shape =',b1d.shape)
print('a2d.shape =',a2d.shape)
print('c2d.shape =',c2d.shape)

print("\n size: numero total de elementos")
print('a1d.size =',a1d.size)
print('b1d.size =',b1d.size)
print('a2d.size =',a2d.size)
print('c2d.size =',c2d.size)

print("\n dtype: tipo dos elementos")
print('a1d.dtype =',a1d.dtype)
print('b1d.dtype =',b1d.dtype)
print('a2d.dtype =',a2d.dtype)
print('c2d.dtype =',c2d.dtype)

print("\n itemsize: tamanho em bytes de cada elemento")
print('a1d.itemsize =',a1d.itemsize)
print('b1d.itemsize =',b1d.itemsize)
print('a2d.itemsize =',a2d.itemsize)
print('c2d.itemsize =',c2d.itemsize)

print("\n data: buffer contendo os elementos do array")
print('a1d.data =',a1d.data)
print('b1d.data =',b1d.data)
print('a2d.data =',a2d.data)
print('c2d.data =',c2d.data)

 ndim: numero de eixos dos arrays
a1d.ndim = 1
b1d.ndim = 1
a2d.ndim = 2
c2d.ndim = 2

 shape: tamanho do array em cada dimensao
a1d.shape = (6,)
b1d.shape = (8,)
a2d.shape = (3, 6)
c2d.shape = (5, 10)

 size: numero total de elementos
a1d.size = 6
b1d.size = 8
a2d.size = 18
c2d.size = 50

 dtype: tipo dos elementos
a1d.dtype = int64
b1d.dtype = float64
a2d.dtype = int64
c2d.dtype = float64

 itemsize: tamanho em bytes de cada elemento
a1d.itemsize = 8
b1d.itemsize = 8
a2d.itemsize = 8
c2d.itemsize = 8

 data: buffer contendo os elementos do array
a1d.data = <memory at 0x107bd1c48>
b1d.data = <memory at 0x107bd1c48>
a2d.data = <memory at 0x107c0e7e0>
c2d.data = <memory at 0x107c0e7e0>


**Importante:** Arrays unidimensionais podem ter uma das dimensões livres. 

In [14]:
a = np.zeros((5))
b = np.zeros((5,1))
print('a.shape = ',a.shape)
print('b.shape = ',b.shape)
print('a.ndim = ',a.ndim)
print('b.ndim = ',b.ndim)

a.shape =  (5,)
b.shape =  (5, 1)
a.ndim =  1
b.ndim =  2


Note que o array cujo <font color='blue'>shape</font> é (5,) possui apenas 1 eixo, enquanto que o array com <font color='blue'>shape</font> (5,1) possui 2 eixos (ndim =2). Este último corresponde a uma matrix com 5 linhas e 1 coluna.

### Acessando os elementos um array
Como no caso de sequências, os índices de um array variam de 0 a $k_i-1$, onde $k_i$ é o número de elementos na dimensão $ i $

In [15]:
# Acessando elementos do array
# Índices variam de 0 a ki-1 em cada dimensão, onde ki é o número de elementos no dimensão i
print(a1d)
print('elemento 0 = ',a1d[0])
print('elemento de indice 3 = ',a1d[3])
print('ultimo elemento do array = ',a1d[-1]) # -1 corresponde ao último elemento do array

print(5*'-')
print(a2d)
print('linha de indice 1 = ',a2d[1]) # quando apenas um índice é fornecido 
                                     # para um array bidimensional
                                     # o que é retornado é a linha correspondente 
                                     # ao índice fornecido
            
print('elemento na linha 0 coluna 1 = ',a2d[0,1])
print('elemento na linha 1 coluna 2 = ',a2d[1,2])
print('elemento na ultima linha e ultima coluna = ',a2d[-1,-1])

[ 1  3  5  7  9 10]
elemento 0 =  1
elemento de indice 3 =  7
ultimo elemento do array =  10
-----
[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]
linha de indice 1 =  [ 2  4  6  8 10 12]
elemento na linha 0 coluna 1 =  3
elemento na linha 1 coluna 2 =  6
elemento na ultima linha e ultima coluna =  5


#### Percorrendo elementos com laço <font color='blue'>for</font>
A iteração é feita por linhas, se o que se busca são os elementos, deve-se utilizar um laço duplo ou então a versão 'flat' do array.

In [18]:
# percorrendo as linhas
for i,r in enumerate(a2d): # o comando 'enumerate' enumera a iteração e retorna o elemento
    print('linha ',i,' = ',r)
    
print(5*'--',' iterando o array')
# percorrendo elementos
for i,r in enumerate(a2d):
    for j,e in enumerate(r):
        print('elemento ',i,' ',j,' = ',e)
        
print(5*'--',' utilizando indices')
# pode-se também utilizar indices diretamente
for i in range(a2d.shape[0]):      # .shape[0] fornece numero linhas
    for j in range(a2d.shape[1]):  # .shape[1] fornece numero colunas
        print('elemento ',i,' ',j,' = ',a2d[i,j])
    
print(5*'--',' utilizando flat')
# o atributo 'flat' coloca todos os elementos como em uma lista
for i in a2d.flat:
    print(i)

linha  0  =  [ 1  3  5  7  9 11]
linha  1  =  [ 2  4  6  8 10 12]
linha  2  =  [0 1 2 3 4 5]
----------  iterando o array
elemento  0   0  =  1
elemento  0   1  =  3
elemento  0   2  =  5
elemento  0   3  =  7
elemento  0   4  =  9
elemento  0   5  =  11
elemento  1   0  =  2
elemento  1   1  =  4
elemento  1   2  =  6
elemento  1   3  =  8
elemento  1   4  =  10
elemento  1   5  =  12
elemento  2   0  =  0
elemento  2   1  =  1
elemento  2   2  =  2
elemento  2   3  =  3
elemento  2   4  =  4
elemento  2   5  =  5
----------  utilizando indices
elemento  0   0  =  1
elemento  0   1  =  3
elemento  0   2  =  5
elemento  0   3  =  7
elemento  0   4  =  9
elemento  0   5  =  11
elemento  1   0  =  2
elemento  1   1  =  4
elemento  1   2  =  6
elemento  1   3  =  8
elemento  1   4  =  10
elemento  1   5  =  12
elemento  2   0  =  0
elemento  2   1  =  1
elemento  2   2  =  2
elemento  2   3  =  3
elemento  2   4  =  4
elemento  2   5  =  5
----------  utilizando flat
1
3
5
7
9
11
2
4
6
8


#### Fatiando arrays (slicing)
A melhor forma de se percorrer um array é por meio de 'slicing', evitando o uso de laços <font color='blue'>for</font>, que são computacionalmente muito menos eficientes.
- Array slicing funciona como em listas, mas em múltiplas dimensões
- Omitir um índice corresponde a recuperar toda a dimensão omitida
- Um slice é uma "visão" (__VIEW__) do array original (similar a uma referencia), isto é, o dado não é copiado

In [21]:
a2d = np.array([[1,3,5,7,9,11],     # criando um array bidimensional a partir de uma
                  [2,4,6,8,10,12],  # lista de listas
                  [0,1,2,3,4,5]])
print(a2d)

# slicing de colunas
print('a2d[1,:] - Recupera a linha de indice 1 (equivalent to a2d[1])\n',a2d[1,:])

# slicing de linhas
print('a2d[:,2] - Recupera a coluna de indice 2\n',a2d[:,2])

# slicing de blocos
print('a2d[1:,2:5] - Recupera o bloco a partir da linha de indice 1 e colunas 2,3 e 4\n',a2d[1:,2:5])

print('a2d[[0,2]] - Recupera as linhas 0 e 2\n',a2d[[0,2]]) 
                                                    # note que uma lista com o indice
                                                    # das linhas é passada para o slicing

print('a2d[:,[0,2,5]] - Recuperando as colunas 0,2 e 5 \n',a2d[:,[0,2,5]]) 
                                                    # note que uma lista com o indice
                                                    # das colunas é passada para o slicing

print('a2d[[0,1,2],[0,2,5]] - Recuperando os elementos das posicoes 0,0 1,2 e 2,5 \n',a2d[[0,1,2],[0,2,5]])
# quando duas listas, uma com indices de linhas e outra com indices de colunas, são passadas
# para o slicing, elementos dos pares de posicoes são recuperados. As duas listas devem
# conter o mesmo número de elementos (indices)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]
a2d[1,:] - Recupera a linha de indice 1 (equivalent to a2d[1])
 [ 2  4  6  8 10 12]
a2d[:,2] - Recupera a coluna de indice 2
 [5 6 2]
a2d[1:,2:5] - Recupera o bloco a partir da linha de indice 1 e colunas 2,3 e 4
 [[ 6  8 10]
 [ 2  3  4]]
a2d[[0,2]] - Recupera as linhas 0 e 2
 [[ 1  3  5  7  9 11]
 [ 0  1  2  3  4  5]]
a2d[:,[0,2,5]] - Recuperando as colunas 0,2 e 5 
 [[ 1  5 11]
 [ 2  6 12]
 [ 0  2  5]]
a2d[[0,1,2],[0,2,5]] - Recuperando os elementos das posicoes 0,0 1,2 e 2,5 
 [1 6 5]


In [26]:
a = np.ones((3,3))
print('a: matrix 3x3')

# Quando uma linha ou coluna é fixada
# o slicing gera um array unidimensional (secunda dimensão livre)
print('Quando uma linha ou coluna é fixada o slicing gera um array unidimensional (segunda dimensão livre)')
print('[:2,1]',a[:2,1].shape) 
print('[:,-1]',a[:,-1].shape)
print('[2]',a[2].shape)
print('[2,:]',a[2,:].shape)

# Quando os símbolo ':' é utilizado
# o slicing fixa a segunda dimensão livre
print('Quando os símbolo ":" é utilizado o slicing fixa a segunda dimensão livre')
print('[2:,:]',a[2:,:].shape)
print('[:2,1:]',a[:2,1:].shape)
print('[:2,-1:]',a[:2,-1:].shape)
print('[:,-1:]',a[:,-1:].shape)

a: matrix 3x3
Quando uma linha ou coluna é fixada o slicing gera um array unidimensional (segunda dimensão livre)
[:2,1] (2,)
[:,-1] (3,)
[2] (3,)
[2,:] (3,)
Quando os símbolo ":" é utilizado o slicing fixa a segunda dimensão livre
[2:,:] (1, 3)
[:2,1:] (2, 2)
[:2,-1:] (2, 1)
[:,-1:] (3, 1)


### Métodos <font color='blue'>flatten</font> , <font color='blue'>ravel</font> e <font color='blue'>reshape</font>
O método <font color='blue'>reshape</font> permite reformadar o array modificando o número de linhas e colunas, porém, a nova 'shape' de possuir o mesmo número de elementos do array original.

O método <font color='blue'>ravel</font> concatena as linhas da matriz em um array unidimensional. 

O método <font color='blue'>flatten</font> também concatena as linhas da matriz em um array unidimensional, porém, faz uma cópia dos elementos. O método <font color='blue'>ravel</font> gera uma __view__, portanto se algum elemento for modificado, o array original também é modificado.

In [29]:
# Criando um array randomico on números entre 0 e 8 e 
# reformatando para a forma de uma matrix 3x3
a = np.arange(9).reshape((3,3))
print('a:\n',a)

# concatenando as linhas de a (ravel não faz cópia)
b = a.ravel()  
print('\nb = a.ravel():\n',b)

# modificando elemento b[2]
b[2] = -2 
print('\nb[2] modificado :',b)

# elemento a[0,2] é afetado pela modificacao de b[2]
print('\nelemento a[0,2] é afetado quando b[2] foi alterado, pois "ravel nao faz copia')
print(a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

b = a.ravel():
 [0 1 2 3 4 5 6 7 8]

b[2] modificado : [ 0  1 -2  3  4  5  6  7  8]

elemento a[0,2] é afetado quand b[2] foi alterado
[[ 0  1 -2]
 [ 3  4  5]
 [ 6  7  8]]


In [33]:
# Criando um array randomico on números entre 0 e 8 e 
# reformatando para a forma de uma matrix 3x3
a = np.arange(9).reshape((3,3))
print('a:\n',a)

# concatenando as linhas de 'a' com flatten()
# uma cópia dos elementos de 'a' é feita
c = a.flatten()
print('\nc = a.flatten():\n',c)


# alterando elemento c[2]
c[2] = -1
print('\nelemento c[2] alterado\n',c)

# elemento a[0,2] NÃO é afetado pela modificacao de c[2]
print('\nelemento a[0,2] NAO e afetado quando c[2] foi alterado, pois "flatten faz copia')
print(a)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

c = a.flatten():
 [0 1 2 3 4 5 6 7 8]

elemento c[2] alterado
 [ 0  1 -1  3  4  5  6  7  8]

elemento a[0,2] NAO e afetado quando c[2] foi alterado, pois "flatten faz copia
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Transposta de uma matriz
A transposta de uma matriz pode ser calculada simplismente invocando o atributo <font color='blue'>.T</font> do objeto 'ndarray'.

In [37]:
a = np.ones((5,3)) # matriz 5x3 com valores 1
print(a)
print(a.shape)

print('\nObtendo a transposta')
a_transposta = a.T
print(a_transposta)
print(a_transposta.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(5, 3)

Obtendo a transposta
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)


### Máscara booleanas
Um array de valores booleanos (máscara booleana) pode ser usado para selecionar elementos em um array.

Máscaras boolenas também podem ser empregadas para fazer atribuições de maneira eficiente e elegante.


In [40]:
# gerando numeros entre 0 e 17 e reformatando em uma matriz 3x6
x = np.arange(18).reshape(3,6)
print(x)

# calculando uma máscara booleana onde o valor True 
# corresponde aos elementos maiores que 7
mask = (x > 7)

print('\nMascara booleana da matriz para valores maiores que 7')
print(mask)

print('\nRecuperando apenas os elementos maiores que 7')
print(x[mask])

print('\nModificando apenas os elementos maiores que 7')
x[mask]=0
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

Mascara booleana da matriz para valores maiores que 7
[[False False False False False False]
 [False False  True  True  True  True]
 [ True  True  True  True  True  True]]

Recuperando apenas os elementos maiores que 7
[ 8  9 10 11 12 13 14 15 16 17]

Modificando apenas os elementos maiores que 7
[[0 1 2 3 4 5]
 [6 7 0 0 0 0]
 [0 0 0 0 0 0]]


### Visualizações  (__view__)
Como visto anteriormente, slicing cria uma __view__ de um array, não uma cópia
- Uma __view__ é criada ao fatiar (slicing) o array
- Uma __view__ é uma referência a uma parte de um array
- Alterar elementos da __view__ afeta o array original
- Se necessário, você pode explicitamente fazer uma cópia utilizando o método <font color='blue'>copy</font>


In [43]:
# gerando numeros 18 números randomicos entre 0 e 10
# e reformatando em uma matriz 3x6
x = np.random.randint(0,10,18).reshape(3,6)

# criando uma view do bloco consistindo das linhas 1 e 2 e das colunas 0,1 e 2
y = x[1:,:3] # y é um view de x
print('Matrix original\n',x)

print('\nView consistindo das linhas 1 e 2 e das colunas 0,1 e 2\n',y)

# modificando um elemento da view
y[1,1] = -1

print('\nModificando um elemento da view também afeta o array original')
print('\nElemento [1,1] da view modificado para -1\n')
print(y)

print('\nMatriz original também é afetada\n')
print(x)

Matrix original
 [[9 6 9 4 4 1]
 [1 2 8 0 0 2]
 [0 0 8 4 5 8]]

View consistindo das linhas 1 e 2 e das colunas 0,1 e 2
 [[1 2 8]
 [0 0 8]]

Modificando um elemento da view também afeta o array original

Elemento [1,1] da view modificado para -1

[[ 1  2  8]
 [ 0 -1  8]]

Matriz original também é afetada

[[ 9  6  9  4  4  1]
 [ 1  2  8  0  0  2]
 [ 0 -1  8  4  5  8]]


In [48]:
# gerando 18 números randomicos entre 0 e 10
# e reformatando em uma matriz 3x6
x = np.random.randint(0,10,18).reshape(3,6)

# criando uma copia do bloco consistindo das linhas 1 e 2 e das colunas 0,1 e 2
y = np.copy(x[1:,:3]) # y é uma copia do bloco de x
print('Matrix original\n',x)

print('\n Copia das linhas 1 e 2 e das colunas 0,1 e 2\n',y)

# modificando um elemento da copia
y[1,1] = -1

print('\nModificando um elemento da copia NAO afeta o array original')
print('\nElemento [1,1] da copia modificado para -1\n')
print(y)

print('\nMatriz original NAO é afetada\n')
print(x)

Matrix original
 [[0 0 2 8 2 3]
 [6 4 0 0 9 8]
 [2 7 1 6 9 4]]

 Copia das linhas 1 e 2 e das colunas 0,1 e 2
 [[6 4 0]
 [2 7 1]]

Modificando um elemento da copia NAO afeta o array original

Elemento [1,1] da copia modificado para -1

[[ 6  4  0]
 [ 2 -1  1]]

Matriz original NAO é afetada

[[0 0 2 8 2 3]
 [6 4 0 0 9 8]
 [2 7 1 6 9 4]]


## I/O com <font color='blue'>numpy</font>
Numpy fornece métodos para ler e escrever arrays em arquivos. A sintaxe básica para leitura de array a partir de arquivo é:
```python
nome_array = np.loadtxt('nome_do_arquivo') # carregando array a partir de um arquivo
```
Os valores no arquivo devem estar separados por espaços e cada linha do arquivo se torna uma linha do array resultante. Vários parâmetros podem ser especificados, veja a documentação do método [loadtxt]()

A sintaxe básica para escrita de array em arquivo é:
```python
nome_array = np.savetxt('nome_do_arquivo',ndarray) # escrevendo array em arquivo
```
Vários parâmetros podem ser especificados, veja a documentação do método [savetxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html)

In [52]:
# gerando 18 números randomicos entre 0 e 10
# e reformatando em uma matriz 3x6
x = np.random.randint(0,10,18).reshape(3,6)

# salvando a matriz x em um arquivo chamado 'exemplo_escrita.txt'
np.savetxt('exemplo_escrita.txt',x,fmt='%d') 

# utilize um editor de texto para verificar o conteudo
# do arquivo 'exemplo_escrita.txt'

In [55]:
# carregando o arquivo 'exemplo_escrita.txt'
x = np.loadtxt('exemplo_escrita.txt',dtype=int) # o parâmetro 'dtype=int' força que os 
                                                # elementos da matriz sejam números inteiros
    
print(x)

x = np.loadtxt('exemplo_escrita.txt') # veja o que acontece 'dtype' não é especificado
print('\nelementos da matriz são do tipo "float"\n')
print(x)

[[2 3 6 0 7 7]
 [0 6 3 4 8 9]
 [4 5 9 9 7 2]]

elementos da matriz são do tipo "float"

[[2. 3. 6. 0. 7. 7.]
 [0. 6. 3. 4. 8. 9.]
 [4. 5. 9. 9. 7. 2.]]
