# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [2]:
import numpy as np

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [22]:
ex1 = np.array([[0,1,2,3,4],
 [5,6,7,8,9],
 [10,11,12,13,14],
 [15,16,17,18,19]])

print(ex1)

print(ex1[1:3,[0,2,3]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  7  8]
 [10 12 13]]


In [25]:
ex2 = np.array([[2,19,16,1,12,7]
,[5,19,18,17,9,3]
,[16,4,18,11,4,2]
,[6,2,18,14,15,15]
,[4,8,1,14,19,13]])

print(ex2)
print(ex2.ndim, ex2.shape, ex2.size)

[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 19 13]]
2 (5, 6) 30


In [29]:
mask1 = (ex2 % 2 == 0)
ex3 = ex2[mask1]
print(ex3.size)
print(ex3)

16
[ 2 16 12 18 16  4 18  4  2  6  2 18 14  4  8 14]


In [34]:
print(ex2.shape)



(5, 6)


In [36]:
l_mask = [j%2!=0 for i in range(ex2.shape[0]) for j in range(ex2.shape[1])]
mask = np.array(l_mask).reshape(ex2.shape)
ex2[mask] = -1

In [37]:
print(ex2)

[[ 2 -1 16 -1 12 -1]
 [ 5 -1 18 -1  9 -1]
 [16 -1 18 -1  4 -1]
 [ 6 -1 18 -1 15 -1]
 [ 4 -1  1 -1 19 -1]]


In [3]:
l = [i for i in range(20)]
A = np.array(l).reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [4]:
A = np.random.randint(0,20,30).reshape(5,6)
print(A)

[[ 8  2 16 12  8 18]
 [14 18 15  5 13 16]
 [11  8 11  1  9  9]
 [ 4 13 10  3  8  7]
 [10  1  8  2 16 16]]


### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [5]:
print('Matriz A:')
print(A,'\n')

A0 = A[[0,1,3]] # linhas de `A` com índices 0,1 e 3
print("linhas de `A` com indices 0,1 e 3")
print(A0,'\n')

A1 = A[1:3,[0,2,4]] # linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
print("linhas de `A` com indice 1 e 2 e colunas com indice 0,2 e 4")
print(A1,'\n')

A2 = A[[1,3]][:,[1,3]] #linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3
print("linhas de `A` com indice 1 e 3 e colunas com indice 1 e 3")
print(A2)

Matriz A:
[[ 8  2 16 12  8 18]
 [14 18 15  5 13 16]
 [11  8 11  1  9  9]
 [ 4 13 10  3  8  7]
 [10  1  8  2 16 16]] 

linhas de `A` com indices 0,1 e 3
[[ 8  2 16 12  8 18]
 [14 18 15  5 13 16]
 [ 4 13 10  3  8  7]] 

linhas de `A` com indice 1 e 2 e colunas com indice 0,2 e 4
[[14 15 13]
 [11 11  9]] 

linhas de `A` com indice 1 e 3 e colunas com indice 1 e 3
[[18  5]
 [13  3]]


### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [6]:
A = np.random.randint(0,20,30).reshape(5,6)
print('A original')
print(A)

Ac = np.copy(A)  # copia de A

maskA = (A > 10)
A[maskA]  = -1
print('\nA modificada com -1 para elementos maiores que 10')
print(A)

maskAc = ((Ac > 7) & (Ac < 15))
Ac[maskAc] = -1
print('\nAc modificada com -1 para elementos maiores que 7 e menores que 15')
print(Ac)

A original
[[15  5 19 14  3  4]
 [ 2 11  0  8 18  9]
 [ 9 10 18 10  7 11]
 [ 5  2 11  0  1  8]
 [16 14 14  7 11  4]]

A modificada com -1 para elementos maiores que 10
[[-1  5 -1 -1  3  4]
 [ 2 -1  0  8 -1  9]
 [ 9 10 -1 10  7 -1]
 [ 5  2 -1  0  1  8]
 [-1 -1 -1  7 -1  4]]

Ac modificada com -1 para elementos maiores que 7 e menores que 15
[[15  5 19 -1  3  4]
 [ 2 -1  0 -1 18 -1]
 [-1 -1 18 -1  7 -1]
 [ 5  2 -1  0  1 -1]
 [16 -1 -1  7 -1  4]]


### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [7]:
A = np.arange(1,201).reshape(20,10)

A_lpares = A[np.arange(0,A.shape[0],2)]
print('A_lpares')
print(A_lpares)

print('\nA_lpares_cimpares')
A_lpares_cimpares = A[np.arange(0,A.shape[0],2)][:,np.arange(1,A.shape[1],2)]
print(A_lpares_cimpares)

A_lpares
[[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 81  82  83  84  85  86  87  88  89  90]
 [101 102 103 104 105 106 107 108 109 110]
 [121 122 123 124 125 126 127 128 129 130]
 [141 142 143 144 145 146 147 148 149 150]
 [161 162 163 164 165 166 167 168 169 170]
 [181 182 183 184 185 186 187 188 189 190]]

A_lpares_cimpares
[[  2   4   6   8  10]
 [ 22  24  26  28  30]
 [ 42  44  46  48  50]
 [ 62  64  66  68  70]
 [ 82  84  86  88  90]
 [102 104 106 108 110]
 [122 124 126 128 130]
 [142 144 146 148 150]
 [162 164 166 168 170]
 [182 184 186 188 190]]


### Exercício 6)
Substitura os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [8]:
mask = [(i%2==0) or (j%2==0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape[0],A.shape[1])
A[mask] = -1

print(A)

[[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  12  -1  14  -1  16  -1  18  -1  20]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  32  -1  34  -1  36  -1  38  -1  40]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  52  -1  54  -1  56  -1  58  -1  60]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  72  -1  74  -1  76  -1  78  -1  80]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  92  -1  94  -1  96  -1  98  -1 100]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 112  -1 114  -1 116  -1 118  -1 120]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 132  -1 134  -1 136  -1 138  -1 140]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 152  -1 154  -1 156  -1 158  -1 160]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 172  -1 174  -1 176  -1 178  -1 180]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 192  -1 194  -1 196  -1 198  -1 200]]


### Exercício 7)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [9]:
X = np.random.uniform(0,1,30).reshape(6,5)
print(X)

X_sorted = sorted(X.ravel())
print('Os tres menores valores: ',X_sorted[0:3])

[[0.60567982 0.1439847  0.56884509 0.62647434 0.97114183]
 [0.43942689 0.68371082 0.82138851 0.4383752  0.75269008]
 [0.64179125 0.30071084 0.08074615 0.18403833 0.20057032]
 [0.05503203 0.05637709 0.163615   0.56716407 0.30635832]
 [0.93452385 0.69428305 0.51311972 0.34150976 0.38119221]
 [0.88181534 0.71715539 0.22900102 0.2837326  0.22736265]]
Os tres menores valores:  [0.05503203006237689, 0.05637708665225061, 0.08074615128150031]


### Exercício 8)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [10]:
def troca_colunas(A,i,j):
    aux = np.copy(A[:,i])
    A[:,i] = A[:,j]
    A[:,j] = aux
    return(A)

X = np.array([[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]])
print(X)

X = troca_colunas(X,1,3)
print(X)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]


### Exercício 9)
Os métodos <font color='blue'>vstack</font> e <font color='blue'>hstack</font> do <font color='blue'>numpy</font> empilha matrizes na vertical e horizontal, respectivamente. Por exemplo:
```python
A = [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
B = [[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]]

C = np.vstack((A,B))
print(C)
```
resulta em
```python
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
```
Escreva um código para gerar duas matrizes `A` e `B` de números inteiros randômicos no intervalo entre 0 e 10, onde:
- A matriz `A` é 5x6
- A matriz `B` é 5x3

Utilize o método <font color='blue'>hstack</font> para empilhar as matrizes

O que acontece se tentar utilizar o método <font color='blue'>vstack</font>? Explique o motivo da mensagem gerada.

In [11]:
A = np.random.randint(0,10,30).reshape(5,6)
B = -1*np.random.randint(0,10,15).reshape(5,3)
print(A)
print(B)

C = np.hstack((A,B))
print(C)

# o método vstack nao pode ser utilizado pois o número de colunas 
# não é o mesmo nas duas matrizes, somente o número de linhas coincide

[[0 0 2 3 5 3]
 [7 1 7 7 6 5]
 [9 5 4 4 1 9]
 [2 3 3 5 8 9]
 [1 8 9 7 7 7]]
[[-3 -1  0]
 [-6 -8 -9]
 [-8 -4 -1]
 [-7 -4 -4]
 [-3 -6  0]]
[[ 0  0  2  3  5  3 -3 -1  0]
 [ 7  1  7  7  6  5 -6 -8 -9]
 [ 9  5  4  4  1  9 -8 -4 -1]
 [ 2  3  3  5  8  9 -7 -4 -4]
 [ 1  8  9  7  7  7 -3 -6  0]]


### Exercício 10)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [12]:
A = np.random.randint(1,10,25).reshape(5,5)

mask = [True if i>j else False for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape[0],A.shape[1])
print(mask)

A[mask] = 0
print(A)

# uma alternativa é utilizar o método 'triu' do numpy
A = np.random.randint(1,10,25).reshape(5,5)
print(A)
A = np.triu(A)
print(A)

[[False False False False False]
 [ True False False False False]
 [ True  True False False False]
 [ True  True  True False False]
 [ True  True  True  True False]]
[[4 5 2 6 4]
 [0 7 5 8 3]
 [0 0 5 8 9]
 [0 0 0 2 6]
 [0 0 0 0 5]]
[[7 5 3 1 8]
 [2 8 3 5 1]
 [5 5 7 2 8]
 [2 1 3 8 3]
 [5 3 5 5 2]]
[[7 5 3 1 8]
 [0 8 3 5 1]
 [0 0 7 2 8]
 [0 0 0 8 3]
 [0 0 0 0 2]]
